fastlane_version "2.66.2"

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"

  lane :tests do

    libraries

    scan

  end

  private_lane :libraries do 

    carthage(
      platform: "iOS"
    )

  end


end
